// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxFihEojSYhVw8hRMzn42hDfWAqEsiUk',
    appId: '1:548437121295:web:5d7eb9b2aa3502c3eb867a',
    messagingSenderId: '548437121295',
    projectId: 'codealpha-fitness-tracke-d9265',
    authDomain: 'codealpha-fitness-tracke-d9265.firebaseapp.com',
    storageBucket: 'codealpha-fitness-tracke-d9265.firebasestorage.app',
    measurementId: 'G-JZ38K2XME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvi-EYqAlnaQ-7r9i1uLKf-SsRF11BaQ',
    appId: '1:548437121295:android:a03b05eff08cc809eb867a',
    messagingSenderId: '548437121295',
    projectId: 'codealpha-fitness-tracke-d9265',
    storageBucket: 'codealpha-fitness-tracke-d9265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwNeL_N9Vh_g2wml3N7q-_XNwzwKiZ3s',
    appId: '1:548437121295:ios:7cbbabbcfe570d08eb867a',
    messagingSenderId: '548437121295',
    projectId: 'codealpha-fitness-tracke-d9265',
    storageBucket: 'codealpha-fitness-tracke-d9265.firebasestorage.app',
    iosBundleId: 'com.example.codealphaFitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwNeL_N9Vh_g2wml3N7q-_XNwzwKiZ3s',
    appId: '1:548437121295:ios:7cbbabbcfe570d08eb867a',
    messagingSenderId: '548437121295',
    projectId: 'codealpha-fitness-tracke-d9265',
    storageBucket: 'codealpha-fitness-tracke-d9265.firebasestorage.app',
    iosBundleId: 'com.example.codealphaFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRxFihEojSYhVw8hRMzn42hDfWAqEsiUk',
    appId: '1:548437121295:web:59c237d83abd76b4eb867a',
    messagingSenderId: '548437121295',
    projectId: 'codealpha-fitness-tracke-d9265',
    authDomain: 'codealpha-fitness-tracke-d9265.firebaseapp.com',
    storageBucket: 'codealpha-fitness-tracke-d9265.firebasestorage.app',
    measurementId: 'G-H2S6BYMBBL',
  );

}